### PR TITLE
Add a constraint optimization study

### PR DESCRIPTION
**Pull request by c-bata**
Add a test case for  constraint optimization example. Please check out https://github.com/optuna/optuna/pull/4793 for the motivation.

Screenshot 2023-07-14 19 51 41

### CODE REVIEW

**Comment by c-bata** [comment]
@not522 @hrntsm Could you review this PR?

**Comment by not522** [comment]
Sorry for my late response. I found the optimization fails to find feasible parameter set sometimes. Could you relax the constraints?

**Comment by c-bata** [comment]
@not522 Sorry for the very very late response. I've pushed changes to relax constraints.

**Before:**

Screenshot 2024-07-25 16 55 45

**After:**

Screenshot 2024-07-25 16 58 21

**Review by not522 — APPROVED** [review]
LGTM

**Pull request merged**
